[package]
name = "bevy-showcase"
version = "0.1.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
rand = "0.7.3"
ncollide2d = "0.24.0"
bevy_rapier2d = "*"


# The following is required so that the bevy crate and the bevy_rapied2d crate reference
# the same version of bevy.
# Without you can have a 'missing bevy::Plugin trait' when load the Rapier2dEnginePlugin
[patch.crates-io]
bevy= {git="https://github.com/bevyengine/bevy"}
